In [1]:
import numpy as np
arr = np.array([24,34,54,65,67,5.3,'karate'])
arr

array(['24', '34', '54', '65', '67', '5.3', 'karate'], dtype='<U32')

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.dtype    

dtype('<U32')

In [15]:
arr.size   # to check size of array...

7

In [14]:
arr.ndim   # to check dimension of array....

1

In [10]:
np.__version__  

'2.0.0'

In [2]:
ar = np.array([24,34,54,65,67,43,54,65])
print(ar[1:4])

[34 54 65]


In [3]:
arr[-1] = 500
arr ** 2

TypeError: ufunc 'square' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

2d - arrays

In [4]:
ls = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(ls)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a.shape

(3, 3)

In [6]:
a[1:,1:]
a[-2:,1:]

array([[5, 6],
       [8, 9]])

In [20]:
a[-1,-1] = 90
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 90]])

In [22]:
ar1 = np.random.randint(1,200,500)
ar1

array([182, 126,  66, 176, 109,  97, 186, 121,  37, 129, 150, 191,  33,
        95,  66,  50,  26,  75, 116, 176, 161, 114, 101, 170, 101,  85,
         9, 189,  53,  34, 128,  48, 162,  24, 132, 183,  77, 125, 137,
       173, 197, 161,  32, 119, 126,  39,  40, 122, 177,  26, 131, 194,
       150,  72, 135,  66, 141,  16, 136,  20,  96,   3, 138, 153, 173,
       134,  37, 106, 173,  90, 102, 153,  68,  79, 162,  79, 173,   8,
         2, 156,  38, 178, 111, 173,  91, 145, 147, 190,  94,   7,  98,
        27, 146, 192,  15,  32, 184,   5,  21, 176, 135, 137,  16,  82,
       139,  99,   5, 158, 186, 164, 161,  45,  89,  26, 130, 183, 180,
        22,  12, 179,  96,  17,  27,   5,  45, 199, 135,  48,   4, 127,
        85, 158, 155,  28, 144, 189, 124,  40,  54, 172, 122, 137, 179,
       171,  98, 177,   2, 116, 114, 134, 176, 140,  72, 154, 105,  85,
        31,  52, 152, 172, 189, 172, 177,  44,   9, 188,   4,  31, 121,
       147, 173, 136,  96,  58, 195,  81,  21,  27,  84, 143,  1

In [23]:
print(ar1[ar1 <= 100])
ar1[ar1 <= 100].size

[66 97 37 33 95 66 50 26 75 85  9 53 34 48 24 77 32 39 40 26 72 66 16 20
 96  3 37 90 68 79 79  8  2 38 91 94  7 98 27 15 32  5 21 16 82 99  5 45
 89 26 22 12 96 17 27  5 45 48  4 85 28 40 54 98  2 72 85 31 52 44  9  4
 31 96 58 81 21 27 84 13 30 23 20 10 36 89  2 32 24 48 89 33  5 23 29 19
 30 74  2  1 38 46  8 56 16 69 45 88 13 82 57 14 54 69 61 51 76 48 14 73
 95 39 34 63 16 54  2 71 45 17 12 15 55 73 13 12 42 63 29 17 84 15 88 99
 93 94 98 23 53 44 59 84 38 22 95 55 29 55 91 69 53 13 28 53 75  3 32 81
 84 17 15 49 83 16 77 15 49  5 42 63 88 16  8 60  3  8 60 42 87 98 55 65
 20 84  6 43 75 65 28 95  6 35 62 44 50 36  9 97 88 63 90 94 82  3 80 37
 49 39 11 25 83 20 46 84 70 25 60 20 31 57 93  6 54 62 41 27 15]


237

In [24]:
ar2 = np.random.randint(1,200,(10,5))
ar2

array([[ 95,  54,  28, 102,  57],
       [175, 195, 117,  95,  29],
       [ 44, 124,  98, 180,  41],
       [ 39, 133,  58, 139,  53],
       [129,  43, 109, 177, 189],
       [187, 114,  68,   2, 150],
       [136,  90, 196,  56,  92],
       [129, 194, 102,  32, 119],
       [ 87, 142,  29,  74,   8],
       [150,   6,  44, 166, 126]], dtype=int32)

In [25]:
ar3 = np.zeros((10,5))
ar3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
ls = [0,1,2,3,4,5,6,7,8,9]
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
ls = list(range(10))
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
ar4 = np.arange(10,101,10)
ar4

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [29]:
ar5 = np.arange(60)
ar5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [30]:
ar5.reshape(10,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [ ]:
ar6 = np.random.randint(1,200,(3,5,4))   # (3 table , 5 row , 4 column)
ar6

array([[[ 90,  13,  19, 188],
        [147,  87, 190, 114],
        [ 89, 132,   5,   1],
        [ 76,  14, 124,  14],
        [116,  23, 120,   4]],

       [[ 68,  58, 190,  24],
        [152,  77, 141,   5],
        [192,  58, 191, 188],
        [152,  34, 165,  19],
        [106, 196, 122, 173]],

       [[123,  64,  14, 162],
        [ 45, 149,  18,  54],
        [ 14, 173, 130, 194],
        [143, 161,  47,  81],
        [119,  46, 147, 180]]], dtype=int32)

In [8]:
print(ar6[2,0:2,1:])
ar6[0:,0]        #[ table , row]

[[ 64  14 162]
 [149  18  54]]


array([[ 90,  13,  19, 188],
       [ 68,  58, 190,  24],
       [123,  64,  14, 162]], dtype=int32)

In [9]:
arr = np.array([9,7,8])
arr

array([9, 7, 8])

some important function.....

In [10]:
print(np.mean(arr))
print(np.sum(arr))
print(max(arr))
print(np.argmin(arr))     # argmin return index of minimum item
print(np.argmax(arr))     # argmax return index of maximum item
arr.sort()
arr                       # ascending order
arr[::-1]                 # desending order

8.0
24
9
1
0


array([9, 8, 7])